#!/usr/bin/env bash

vagrant=""

function vagrant {
  command "${vagrant[@]}" "$@"
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  
  set -x

  if [[ "$#" -gt 0 ]]; then
    local net_lxd="$1"; shift
    local net_host="$1"; shift

    rm -rf "$LXD_CONF"
    mkdir -p "$LXD_CONF"

    "${BASEBOX_INSTANCE}" vagrant ssh -- sudo service lxd stop 2>/dev/null || true

    cat <<EOF | "${BASEBOX_INSTANCE}" vagrant ssh -- sudo tee /etc/default/lxd-bridge
USE_LXD_BRIDGE="true"
LXD_BRIDGE="lxdbr0"
UPDATE_PROFILE="true"
LXD_CONFILE=""
LXD_DOMAIN="${BASEBOX_INSTANCE}"
LXD_IPV4_ADDR="${net_lxd}.1"
LXD_IPV4_NETMASK="255.255.255.0"
LXD_IPV4_NETWORK="${net_lxd}.1/24"
LXD_IPV4_DHCP_RANGE="${net_lxd}.10,${net_lxd}.200"
LXD_IPV4_DHCP_MAX="191"
LXD_IPV4_NAT="true"
LXD_IPV6_ADDR=""
LXD_IPV6_MASK=""
LXD_IPV6_NETWORK=""
LXD_IPV6_NAT="false"
LXD_IPV6_PROXY="false"
EOF

      cat <<EOF | "${BASEBOX_INSTANCE}" vagrant ssh -- sudo tee /etc/network/interfaces.d/99-limbo-fan.cfg
auto lxdbr0
iface lxdbr0 inet manual
  up ip addr add "${net_host}.1/24" dev lxdbr0:0
  up fanctl up -o 250.0.0.0/8 -u "${net_host}.1/16"
EOF

    "${BASEBOX_INSTANCE}" vagrant ssh -- sudo service lxd start

    vagrant=("${BASEBOX_INSTANCE}" vagrant ssh --)
    local ip_dream="$BASEBOX_IP"
  else
    vagrant=("${BASEBOX_DREAM}" lxc exec "${BASEBOX_INSTANCE}" --)
    local ip_dream="$("${BASEBOX_DREAM}" lxc list --format=json "${BASEBOX_INSTANCE}" | jq -r '.[] | .state.network.eth0.addresses[] | select(.scope == "global") | .address')"
  fi

  local lxd_pass="${RANDOM}-$$-$(date +%s)"

  vagrant sudo lxc config set core.https_address '[::]'
  vagrant sudo lxc config set core.trust_password "$lxd_pass"

  lxc remote rename "$BASEBOX_INSTANCE" "$BASEBOX_INSTANCE"old 2>/dev/null || true
  lxc remote add --accept-certificate "$BASEBOX_INSTANCE" "$ip_dream" --password="$lxd_pass"
  lxc remote set-default "$BASEBOX_INSTANCE" 
  lxc remote remove "$BASEBOX_INSTANCE"old 2>/dev/null || true

  lxc profile set default security.nesting true
  lxc profile set default security.privileged false

  vagrant lxc image copy ubuntu:16.04 local: --alias xenial

  lxc profile create limbo 2>/dev/null || true
  lxc profile set limbo user.user-data - < "$shome/cidata/user-data"
}

source sub "$BASH_SOURCE" "$@"
