#!/usr/bin/env bash

export MACHINE_STORAGE_PATH="${CACHE_DIR}/.docker/machine"
export VAGRANT_DEFAULT_PROVIDER='docker'

eval $(docker machine env --no-proxy "${BASEBOX_MACHINE:-$BASEBOX_INSTANCE}" 2>/dev/null)

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  exec docker "$@"
}

source sub "$BASH_SOURCE" "$@"
